from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(632, 613)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 435))
        self.centralwidget.setMaximumSize(QtCore.QSize(793, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 70, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.x_coordinate_input = QtWidgets.QLineEdit(self.centralwidget)
        self.x_coordinate_input.setGeometry(QtCore.QRect(100, 20, 100, 20))
        self.x_coordinate_input.setObjectName("x_coordinate_input")
        self.y_coordinate_input = QtWidgets.QLineEdit(self.centralwidget)
        self.y_coordinate_input.setGeometry(QtCore.QRect(290, 20, 100, 20))
        self.y_coordinate_input.setObjectName("y_coordinate_input")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 20, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(6, 0, 621, 121))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(14, 50, 70, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.combo_box = QtWidgets.QComboBox(self.groupBox)
        self.combo_box.setGeometry(QtCore.QRect(94, 50, 100, 22))
        self.combo_box.setObjectName("combo_box")
        self.combo_box.addItem("")
        self.combo_box.addItem("")
        self.combo_box.addItem("")
        self.combo_box.addItem("")
        self.combo_box.addItem("")
        self.combo_box.addItem("")
        self.combo_box.addItem("")
        self.combo_box.addItem("")
        self.combo_box.addItem("")
        self.combo_box.addItem("")
        self.repeat_count = QtWidgets.QLineEdit(self.groupBox)
        self.repeat_count.setGeometry(QtCore.QRect(284, 50, 100, 20))
        self.repeat_count.setObjectName("repeat_count")
        self.add_button = QtWidgets.QPushButton(self.groupBox)
        self.add_button.setGeometry(QtCore.QRect(400, 12, 101, 41))
        self.add_button.setObjectName("add_button")
        self.save_button = QtWidgets.QPushButton(self.groupBox)
        self.save_button.setGeometry(QtCore.QRect(400, 62, 101, 41))
        self.save_button.setObjectName("save_button")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(14, 80, 70, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.delay_input = QtWidgets.QLineEdit(self.groupBox)
        self.delay_input.setGeometry(QtCore.QRect(94, 80, 100, 20))
        self.delay_input.setObjectName("delay_input")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(200, 80, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.load_button = QtWidgets.QPushButton(self.groupBox)
        self.load_button.setGeometry(QtCore.QRect(510, 12, 101, 41))
        self.load_button.setObjectName("load_button")
        self.save_as_button = QtWidgets.QPushButton(self.groupBox)
        self.save_as_button.setGeometry(QtCore.QRect(510, 62, 101, 41))
        self.save_as_button.setObjectName("save_as_button")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(213, 50, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.shortcuts_group = QtWidgets.QGroupBox(self.centralwidget)
        self.shortcuts_group.setGeometry(QtCore.QRect(6, 130, 621, 111))
        self.shortcuts_group.setObjectName("shortcuts_group")
        self.label_6 = QtWidgets.QLabel(self.shortcuts_group)
        self.label_6.setGeometry(QtCore.QRect(14, 20, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.shortcuts_group)
        self.label_7.setGeometry(QtCore.QRect(14, 50, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.get_mouse_position_shortcut = QtWidgets.QLineEdit(self.shortcuts_group)
        self.get_mouse_position_shortcut.setGeometry(QtCore.QRect(120, 22, 101, 20))
        self.get_mouse_position_shortcut.setText("")
        self.get_mouse_position_shortcut.setObjectName("get_mouse_position_shortcut")
        self.execute_script_shortcut = QtWidgets.QLineEdit(self.shortcuts_group)
        self.execute_script_shortcut.setGeometry(QtCore.QRect(120, 52, 101, 20))
        self.execute_script_shortcut.setText("")
        self.execute_script_shortcut.setObjectName("execute_script_shortcut")
        self.apply_position_shortcut = QtWidgets.QPushButton(self.shortcuts_group)
        self.apply_position_shortcut.setGeometry(QtCore.QRect(240, 20, 75, 23))
        self.apply_position_shortcut.setObjectName("apply_position_shortcut")
        self.apply_execution_shortcut = QtWidgets.QPushButton(self.shortcuts_group)
        self.apply_execution_shortcut.setGeometry(QtCore.QRect(240, 50, 75, 23))
        self.apply_execution_shortcut.setObjectName("apply_execution_shortcut")
        self.label_9 = QtWidgets.QLabel(self.shortcuts_group)
        self.label_9.setGeometry(QtCore.QRect(320, 22, 91, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.shortcuts_group)
        self.label_10.setGeometry(QtCore.QRect(320, 52, 101, 16))
        self.label_10.setObjectName("label_10")
        self.Actions_box = QtWidgets.QGroupBox(self.centralwidget)
        self.Actions_box.setGeometry(QtCore.QRect(6, 250, 621, 311))
        self.Actions_box.setObjectName("Actions_box")
        self.macro_table = QtWidgets.QTableWidget(self.Actions_box)
        self.macro_table.setGeometry(QtCore.QRect(10, 20, 461, 271))
        self.macro_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.macro_table.setObjectName("macro_table")
        self.macro_table.setColumnCount(5)
        self.macro_table.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.macro_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.macro_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.macro_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.macro_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.macro_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.macro_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.macro_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.macro_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.macro_table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.macro_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.macro_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.macro_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.macro_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.macro_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.macro_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.macro_table.setItem(0, 1, item)
        self.delete_all_button = QtWidgets.QPushButton(self.Actions_box)
        self.delete_all_button.setGeometry(QtCore.QRect(500, 80, 101, 51))
        self.delete_all_button.setObjectName("delete_all_button")
        self.delete_button = QtWidgets.QPushButton(self.Actions_box)
        self.delete_button.setGeometry(QtCore.QRect(500, 150, 101, 51))
        self.delete_button.setObjectName("delete_button")
        self.groupBox.raise_()
        self.label.raise_()
        self.x_coordinate_input.raise_()
        self.y_coordinate_input.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.shortcuts_group.raise_()
        self.Actions_box.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 632, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "X-Coordinate: "))
        self.label_2.setText(_translate("MainWindow", " Y-Coordinate: "))
        self.groupBox.setTitle(_translate("MainWindow", "Add/Edit "))
        self.label_3.setText(_translate("MainWindow", "Key Press:"))
        self.combo_box.setItemText(0, _translate("MainWindow", "Left Click"))
        self.combo_box.setItemText(1, _translate("MainWindow", "Right Click"))
        self.combo_box.setItemText(2, _translate("MainWindow", "Shift"))
        self.combo_box.setItemText(3, _translate("MainWindow", "Tab"))
        self.combo_box.setItemText(4, _translate("MainWindow", "Enter"))
        self.combo_box.setItemText(5, _translate("MainWindow", "Page Up"))
        self.combo_box.setItemText(6, _translate("MainWindow", "Page Down"))
        self.combo_box.setItemText(7, _translate("MainWindow", "Ctrl"))
        self.combo_box.setItemText(8, _translate("MainWindow", "Alt"))
        self.combo_box.setItemText(9, _translate("MainWindow", "Delete"))
        self.add_button.setText(_translate("MainWindow", "Add"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.label_5.setText(_translate("MainWindow", "Delay:"))
        self.label_8.setText(_translate("MainWindow", "Seconds (ms)"))
        self.load_button.setText(_translate("MainWindow", "Load"))
        self.save_as_button.setText(_translate("MainWindow", "Save As"))
        self.label_4.setText(_translate("MainWindow", "Repeat count:"))
        self.shortcuts_group.setTitle(_translate("MainWindow", "Keyboard Shortcuts"))
        self.label_6.setText(_translate("MainWindow", "Get Mouse Position: "))
        self.label_7.setText(_translate("MainWindow", "Execute Script: "))
        self.apply_position_shortcut.setText(_translate("MainWindow", "Apply"))
        self.apply_execution_shortcut.setText(_translate("MainWindow", "Apply"))
        self.label_9.setText(_translate("MainWindow", "(Default key is F8)"))
        self.label_10.setText(_translate("MainWindow", "(Default key is F2)"))
        self.Actions_box.setTitle(_translate("MainWindow", "Actions"))
        item = self.macro_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.macro_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.macro_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.macro_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.macro_table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.macro_table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.macro_table.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "8"))
        item = self.macro_table.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "9"))
        item = self.macro_table.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "10"))
        item = self.macro_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Action"))
        item = self.macro_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "X"))
        item = self.macro_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Y"))
        item = self.macro_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Delay (ms)"))
        item = self.macro_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Repeat"))
        __sortingEnabled = self.macro_table.isSortingEnabled()
        self.macro_table.setSortingEnabled(False)
        self.macro_table.setSortingEnabled(__sortingEnabled)
        self.delete_all_button.setText(_translate("MainWindow", "Delete All"))
        self.delete_button.setText(_translate("MainWindow", "Delete"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionSave_as.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As.."))
